### ISSUE TITLE
Auto update Content-Length header value while sending request from ATOR

### ISSUE THREAD

**Issue by 0p71mu5** [synopsys-sig/ATOR-Burp#15]
When sending a request with modified response data, the content length in the request header should automatically be updated based on the length of data being sent.

This is causing issues when the data to be inserted in the next request is of variable length. 

Let's consider the below scenario during configuration:
Request1 -> Response1 (data fetched of length 8 chars)
Request2 (sent with data of 8 chars) -> Result Response.
Here, the Content-Length is of 8 characters is saved in the config by default.

Now let's consider the above scenario with data fetched greater than 8 chars:
Request1 -> Response1 (data fetched of length 15 chars)
Request2 (sent with data of 15 chars) -> Error Result
Here only the first 8 characters among 15 were sent as the original Content-Length value saved in the config was 8 chars. Hence, the server is getting less than the expected data, resulting into error.

In the below example, due to content length issue, the end `"}` is being truncated by ATOR and not being sent to server (even if it is shown in logger):
![image](https://user-images.githubusercontent.com/11387975/130982454-ffabc140-3b02-44bc-8b13-8e11a31f8b11.png)
(got to know the actual value being sent in fiddler as logger was showing that expected data is being sent)

Expected Request Data to be sent by ATOR:
![image](https://user-images.githubusercontent.com/11387975/130982646-f98cf3e5-01f9-4296-af5c-c556b20f77d9.png)

**Comment by Manikandan-Raj** [comment]
That issue was fixed in V2, please take a binaries from /v2/bin and try with the scenario

**Comment by my127001** [comment]
In version 2.1 from BApp Store problem still exist 
![image](https://user-images.githubusercontent.com/74767988/210111774-2bea96e5-3eb8-47c8-a5c2-8f2759a423f1.png)

Request sent from repeater:
![image](https://user-images.githubusercontent.com/74767988/210111836-e038221f-493e-4ff5-9ac3-21eb87b9e65b.png)

With ATOR turned on from logger:
![image](https://user-images.githubusercontent.com/74767988/210111869-3ed1e875-f2a6-4df3-87f9-bc89a8cc7ae3.png)

With ATOR turned off:
![image](https://user-images.githubusercontent.com/74767988/210111934-b30e48e6-5f11-46f4-8238-926d773e3437.png)
